# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' d_snb
#' @name d_snb
#' @param x numeric value or vector
#' @param size_param,prob_param,mu_param,size,prob,mu
#'     numeric value or vector,
#'     atleast two of these parameters must be specified
#' @param infinite integer value specifying the maximum number
#'     of terms to compute in the series, default: 100000
#' @param log_v,log whether the results should be log values,
#'     default: false
#' @importFrom Rcpp evalCpp
#' @useDynLib stochprofML
#' @export
d_snb <- function(x, size_param = NULL, prob_param = NULL, mu_param = NULL, infinite = 100000L, log_v = FALSE) {
    .Call('_stochprofML_d_snb', PACKAGE = 'stochprofML', x, size_param, prob_param, mu_param, infinite, log_v)
}

